$path = "d:\vv\js\dashboard.js"
$content = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
$content = $content.Replace("条斁E", "条文")
$content = $content.Replace("契紁E", "契約")
$content = $content.Replace("完亁E", "完了")
$content = $content.Replace("佁E", "低")
$content = $content.Replace("髁E", "高")
$content = $content.Replace("改訁E", "改訂")
$content = $content.Replace("未確誁E", "未確認")
$content = $content.Replace("未処琁E", "未処理")
$content = $content.Replace("未解极E", "未解析")
$content = $content.Replace("斁EぁE", "本文がありません")
$content = $content.Replace("征Eください、E", "待ちください。")
[System.IO.File]::WriteAllText($path, $content, [System.Text.Encoding]::UTF8)
