[build]
  publish = "."
  functions = "netlify/functions"
  [build.environment]
    SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "/api/paypal-checkout"
  to = "/.netlify/functions/paypal-checkout"
  status = 200
  force = true

[[redirects]]
  from = "/api/paypal-checkout/"
  to = "/.netlify/functions/paypal-checkout"
  status = 200
  force = true
